spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true


    hibernate:
      ddl-auto: update
    generate-ddl: false
  liquibase:
    change-log: db/changelog/changelog.xml
